### ISSUE TITLE
The reason for "+1" and "-1" in line 1068 in pi_zero.py

### ISSUE THREAD

**Issue by HappyFern666** [lucidrains/pi-zero-pytorch#12]
Hi there! Thanks for sharing the codes!

There is some thing driving me confused in pi_zero.py, in line 1068, here is
mask = F.pad(language_mask, (state_length - command_length - 1, 1 + action_with_registers_length), value = True).

And I wonder why there are "-1" and "+1", are they for marker tokens?

**Comment by lucidrains** [comment]
@HappyFern666 hey Xuchuan, it was for the joint state token, in an older version, but now that it has been moved (along with other internal state tokens) to the action branch, it is no longer needed

thank you for raising this!
