### ISSUE TITLE
flow matching objective correction?

### ISSUE THREAD

**Issue by jkim447** [lucidrains/pi-zero-pytorch#13]
Are these lines the correct implementation of flow matching?:

https://github.com/lucidrains/pi-zero-pytorch/blob/8ad66fdc5f5749e93beeb083b7c9146e6187d66a/pi_zero_pytorch/pi_zero.py#L985C1-L995C56

Shouldn't the flow be something like: `actions - noise`, where `noise = noise.lerp(actions, padded_times)`?

Basically the flow should be defined as the difference between the ground truth actions and the noise after the lerping is performed, rather than subtracting by originally sampled raw noise. My intuition might not be correct here but wanted to double check.

**Comment by lucidrains** [comment]
I've always thought it was the vector from initial noise to data, but curious how the network would behave if you predicted what you propose

probably not a huge difference

**Comment by lucidrains** [comment]
@jkim447 algorithm 2 in https://arxiv.org/abs/2209.03003

**Comment by jkim447** [comment]
Ah I see where this came from. Thanks for clarifying!
