### ISSUE TITLE
Current state of pi-zero-pytorch repo vs transfusion-pytorch for training experiments

### ISSUE THREAD

**Issue by dusty-nv** [lucidrains/pi-zero-pytorch#2]
Hi @lucidrains, thank you for your amazing work and contributions!   I am interested in running some open test trainings of these Transfusion-based models you have implemented.  I have been gathering/labelling higher-quality image and video data geared for edge use-cases.  I will share the results, datasets, and checkpoints of these, and am happy to collaborate with everyone.

Whats gaps/TODOs have you identified on the π0 repo?   It would seem your transfusion-pytorch repo is in a slightly more mature state currently, and was planning to start there with image->text pre-training for embedded vision tasks with structured I/O.  I'd like to characterize these models and ramp up the complexity adding modalities (images, video, audio, IMU/proprioception) 

In addition to ego-centric embodiment for robotics, also interested in exo-centric IoT/vision devices for public safety, assistive devices, anomaly detection, scene/landmark recognition & navigation, ect. Our hope is that with carefully curated real-world data (and possibly continual learning or KTO), anyone can deploy these mini multimodal models for edge domains with intuitive on-device workflows and user personalization/adaptation, instead of frustrating prompt engineering of internet-trained chat models.  

Our background:  I'm from the Jetson team at NVIDIA and [jetson-ai-lab.com](https://www.jetson-ai-lab.com/).  We have previously done optimizations for streaming VLMs, OpenVLA training, HF LeRobot, ect.  I have A100/H100 spot instances for the training and data curation.  I'm good with the workflows/infra and embedded optimizations, and while I conceptually understand the papers, implementing new SOTA transformer architectures is not my forte.  You seem amazingly active across your GitHub, and with your confidence am happy to work together along with the community to help prove these out :+1:

**Comment by lucidrains** [comment]
@dusty-nv hey Dustin, thank you for your interest

would you like to chat over Signal more informally? i can give you a rundown of my situation and my plans for the upcoming months for the robotics and RL space.

**Comment by lucidrains** [comment]
@dusty-nv nvidia has a robotics team being led by Jim Fan? i'm curious why you would reach out to me, unless if they are to be part of the collaborative group?

**Comment by dusty-nv** [comment]
@lucidrains yes, happy to chat on Signal - although I admit, not certain how to find you there (I'll email you my contact info)

And yes, I/we work with the Groot team, Isaac, Metropolis, ROS community, LeRobot, ect on the embedded side.  Our particular remit is to enable everyone and the community with the latest open-source models/workflows/frameworks for edge.  At [jetson-containers](https://github.com/dusty-nv/jetson-containers) we have built up a large amount of genAI infra to enable this for ARM64+CUDA built from scratch.  

Think of us like a quick-reaction force to ungate people from trying the latest promising open-source stuff, building support for what early-adopters & researchers can get started with today and experiment with for practical automations.  Then that gives teams like Groot the longer-term focus to develop massive-scale foundation models and production-grade solutions to converge around, for example scaling to >30DoF humanoids.  

Meanwhile today, ourselves and others are beginning to deploy it for less complex utilitarian scenarios.  Many of us long-time Jetson users have things in mind we already want to use it for - for example, outdoor learning robots with basic manipulation.  In my case I grew up farming, so my personal connection is with agtech (I noticed [*Dear Alice*](https://www.youtube.com/watch?v=z-Ng5ZvrDm4) at the bottom of your readme :smiling_face_with_tear:)

**Comment by lucidrains** [comment]
@dusty-nv Groot is a great name for a team! yes i understand your goals now. can chat more through email

re: agtech, indeed, i think it has already begun (weed management with computer vision for instance), but the effects could be broader as solar, energy storage, and AI all come together into something more unified. we'll just have to see how far RL + foundation models can really be pushed.

**Comment by dusty-nv** [comment]
@lucidrains closing this issue for now -  been proceeding with working on transfusion for now.  I sent a couple emails to your gmail this week - no rush, but if you haven't received them ping me or try `dustinf@nvidia.com` 👍

**Comment by lucidrains** [comment]
@dusty-nv hey Dusty, apologies for the late reply. I will get back to your email later today

Transfusion should be good, but just note in this paper they found out that actions requires their own separate parameters, which is why I decided to just rebuild it. I do plan on adding mixture of experts to Transfusion, but that may be in month of December
