### ISSUE TITLE
Position of joint states

### ISSUE THREAD

**Issue by Frankluox** [lucidrains/pi-zero-pytorch#8]
Hi, thanks for your work, I have gone through the code and found that the `joint state` tokens are put in the VLM branch instead of in the action branch, different from the original pi-0 paper where the `joint state` tokens are put in the action branch of the network. Is this a mistake or an intended change? 
Thanks.

**Comment by lucidrains** [comment]
@Frankluox hey Xu, yes indeed that is an error on my part

i will correct this after the holidays mid next week, thank you

**Comment by lucidrains** [comment]
very appropriate avatar lol

**Comment by Frankluox** [comment]
Thank you! Glad you like it 😄. Looking forward to the update.

**Comment by lucidrains** [comment]
@Frankluox is few shot learning research really dead? noticed that in your bio

**Comment by lucidrains** [comment]
@Frankluox hey Xu, would you like to take a look at the latest version and see if it lines up with your expectations?

**Comment by Frankluox** [comment]
@lucidrains Hi Phil, I've checked the latest version and it looks great now. Thank you for addressing the issue so promptly!

**Comment by Frankluox** [comment]
Regarding the recent question I missed: The field of "traditional few-shot learning" is indeed dead now :)

However, its essence lives on in other areas, such as in-context learning with large language models and few-shot fine-tuning of foundational robotic models, etc.
