### ISSUE TITLE
Clarification about potential mismatch in:ff_ada_rmsnorm/ff_ada_layerscale

### ISSUE THREAD

**Issue by Wonder1905** [lucidrains/pi-zero-pytorch#9]
Hi, small question  to make sure, in line 1163:
`         
                action_tokens = ff_ada_rmsnorm(action_tokens, time_cond)

                action_tokens = actions_ff(action_tokens) + action_tokens

                action_tokens = ff_ada_rmsnorm(action_tokens, time_cond)`
                
I assume it should be:
`         
                action_tokens = ff_ada_rmsnorm(action_tokens, time_cond)

                action_tokens = actions_ff(action_tokens) + action_tokens

                action_tokens = **ff_ada_layerscale**(action_tokens, time_cond)`
                
                
Or Im missing something out.
Thanks

**Comment by lucidrains** [comment]
@Wonder1905 got it fixed just now, it was too embarrassing to have this bug out in the open lol 🤦
